<?php
if (function_exists('acf_add_local_field_group')):

    acf_add_local_field_group(array(
        'key' => 'group_62a8636c43e28',
        'title' => 'Publication Details',
        'fields' => array(
            array(
                'key' => 'field_62a885b26fd91',
                'label' => 'Abstract',
                'name' => 'publication_abstract',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ) ,
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 6,
                'new_lines' => '',
            ) ,
            array(
                'key' => 'field_62a82f61539df',
                'label' => 'Journal',
                'name' => 'publication_journal',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '40',
                    'class' => '',
                    'id' => '',
                ) ,
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ) ,
            array(
                'key' => 'field_62a88742203a6',
                'label' => 'Year',
                'name' => 'publication_year',
                'type' => 'number',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '20',
                    'class' => '',
                    'id' => '',
                ) ,
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'min' => '',
                'max' => '',
                'step' => '',
            ) ,
            array(
                'key' => 'field_62a82fab539e0',
                'label' => 'Volume',
                'name' => 'publication_volume',
                'type' => 'number',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '20',
                    'class' => '',
                    'id' => '',
                ) ,
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'min' => '',
                'max' => '',
                'step' => '',
            ) ,
            array(
                'key' => 'field_62a82fd0539e1',
                'label' => 'Page Number',
                'name' => 'publication_page_number',
                'type' => 'number',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '20',
                    'class' => '',
                    'id' => '',
                ) ,
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'min' => '',
                'max' => '',
                'step' => '',
            ) ,
            array(
                'key' => 'field_62a8319a0804a',
                'label' => 'doi',
                'name' => 'publication_doi',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ) ,
                'default_value' => '',
                'placeholder' => '',
                'prepend' => 'doi.org/',
                'append' => '',
                'maxlength' => '',
            ) ,
            array(
                'key' => 'field_62a859e000a87',
                'label' => 'Authors',
                'name' => 'author_list',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ) ,
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_62a85d354a73e',
                        'label' => 'Author 1',
                        'name' => 'author_1',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ) ,
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_62a85a5d00a8a',
                                'label' => 'First Name',
                                'name' => 'first_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a85cd287f8a',
                                'label' => 'Initials',
                                'name' => 'initials',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a85aa300a8c',
                                'label' => 'Last Name',
                                'name' => 'last_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a85db807d75',
                                'label' => 'Add Another',
                                'name' => 'add_another',
                                'type' => 'true_false',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'message' => '',
                                'default_value' => 0,
                                'ui' => 1,
                                'ui_on_text' => '',
                                'ui_off_text' => '',
                            ) ,
                        ) ,
                    ) ,
                    array(
                        'key' => 'field_62a85ec879ea1',
                        'label' => 'Author 2',
                        'name' => 'author_2',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_62a85db807d75',
                                    'operator' => '==',
                                    'value' => '1',
                                ) ,
                            ) ,
                        ) ,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ) ,
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_62a85ec979ea2',
                                'label' => 'First Name',
                                'name' => 'first_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a85ec979ea3',
                                'label' => 'Initials',
                                'name' => 'initials',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a85ec979ea4',
                                'label' => 'Last Name',
                                'name' => 'last_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a85ec979ea5',
                                'label' => 'Add Another',
                                'name' => 'add_another',
                                'type' => 'true_false',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'message' => '',
                                'default_value' => 0,
                                'ui' => 1,
                                'ui_on_text' => '',
                                'ui_off_text' => '',
                            ) ,
                        ) ,
                    ) ,
                    array(
                        'key' => 'field_62a85f4f60c06',
                        'label' => 'Author 3',
                        'name' => 'author_3',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_62a85ec979ea5',
                                    'operator' => '==',
                                    'value' => '1',
                                ) ,
                            ) ,
                        ) ,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ) ,
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_62a85f4f60c07',
                                'label' => 'First Name',
                                'name' => 'first_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a85f4f60c08',
                                'label' => 'Initials',
                                'name' => 'initials',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a85f4f60c09',
                                'label' => 'Last Name',
                                'name' => 'last_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a85f4f60c0a',
                                'label' => 'Add Another',
                                'name' => 'add_another',
                                'type' => 'true_false',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'message' => '',
                                'default_value' => 0,
                                'ui' => 1,
                                'ui_on_text' => '',
                                'ui_off_text' => '',
                            ) ,
                        ) ,
                    ) ,
                    array(
                        'key' => 'field_62a85f4f60c01',
                        'label' => 'Author 4',
                        'name' => 'author_4',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_62a85f4f60c0a',
                                    'operator' => '==',
                                    'value' => '1',
                                ) ,
                            ) ,
                        ) ,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ) ,
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_62a85f4f60c02',
                                'label' => 'First Name',
                                'name' => 'first_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a85f4f60c03',
                                'label' => 'Initials',
                                'name' => 'initials',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a85f4f60c04',
                                'label' => 'Last Name',
                                'name' => 'last_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a85f4f60c05',
                                'label' => 'Add Another',
                                'name' => 'add_another',
                                'type' => 'true_false',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'message' => '',
                                'default_value' => 0,
                                'ui' => 1,
                                'ui_on_text' => '',
                                'ui_off_text' => '',
                            ) ,
                        ) ,
                    ) ,
                    array(
                        'key' => 'field_62a85f4e60bfc',
                        'label' => 'Author 5',
                        'name' => 'author_5',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_62a85f4f60c05',
                                    'operator' => '==',
                                    'value' => '1',
                                ) ,
                            ) ,
                        ) ,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ) ,
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_62a85f4e60bfd',
                                'label' => 'First Name',
                                'name' => 'first_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a85f4e60bfe',
                                'label' => 'Initials',
                                'name' => 'initials',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a85f4e60bff',
                                'label' => 'Last Name',
                                'name' => 'last_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a85f4e60c00',
                                'label' => 'Add Another',
                                'name' => 'add_another',
                                'type' => 'true_false',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'message' => '',
                                'default_value' => 0,
                                'ui' => 1,
                                'ui_on_text' => '',
                                'ui_off_text' => '',
                            ) ,
                        ) ,
                    ) ,
                    array(
                        'key' => 'field_62a85f4e60bf7',
                        'label' => 'Author 6',
                        'name' => 'author_6',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_62a85f4e60c00',
                                    'operator' => '==',
                                    'value' => '1',
                                ) ,
                            ) ,
                        ) ,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ) ,
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_62a85f4e60bf8',
                                'label' => 'First Name',
                                'name' => 'first_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a85f4e60bf9',
                                'label' => 'Initials',
                                'name' => 'initials',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a85f4e60bfa',
                                'label' => 'Last Name',
                                'name' => 'last_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a85f4e60bfb',
                                'label' => 'Add Another',
                                'name' => 'add_another',
                                'type' => 'true_false',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'message' => '',
                                'default_value' => 0,
                                'ui' => 1,
                                'ui_on_text' => '',
                                'ui_off_text' => '',
                            ) ,
                        ) ,
                    ) ,
                    array(
                        'key' => 'field_62a85f4d60bf2',
                        'label' => 'Author 7',
                        'name' => 'author_7',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_62a85f4e60bfb',
                                    'operator' => '==',
                                    'value' => '1',
                                ) ,
                            ) ,
                        ) ,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ) ,
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_62a85f4d60bf3',
                                'label' => 'First Name',
                                'name' => 'first_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a85f4d60bf4',
                                'label' => 'Initials',
                                'name' => 'initials',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a85f4d60bf5',
                                'label' => 'Last Name',
                                'name' => 'last_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a85f4d60bf6',
                                'label' => 'Add Another',
                                'name' => 'add_another',
                                'type' => 'true_false',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'message' => '',
                                'default_value' => 0,
                                'ui' => 1,
                                'ui_on_text' => '',
                                'ui_off_text' => '',
                            ) ,
                        ) ,
                    ) ,
                    array(
                        'key' => 'field_62a85f4b60bed',
                        'label' => 'Author 8',
                        'name' => 'author_8',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_62a85f4d60bf6',
                                    'operator' => '==',
                                    'value' => '1',
                                ) ,
                            ) ,
                        ) ,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ) ,
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_62a85f4b60bee',
                                'label' => 'First Name',
                                'name' => 'first_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a85f4b60bef',
                                'label' => 'Initials',
                                'name' => 'initials',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a85f4b60bf0',
                                'label' => 'Last Name',
                                'name' => 'last_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a85f4b60bf1',
                                'label' => 'Add Another',
                                'name' => 'add_another',
                                'type' => 'true_false',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'message' => '',
                                'default_value' => 0,
                                'ui' => 1,
                                'ui_on_text' => '',
                                'ui_off_text' => '',
                            ) ,
                        ) ,
                    ) ,
                    array(
                        'key' => 'field_62a8626d5882a',
                        'label' => 'Author 9',
                        'name' => 'author_9',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_62a85f4b60bf1',
                                    'operator' => '==',
                                    'value' => '1',
                                ) ,
                            ) ,
                        ) ,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ) ,
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_62a8626d5882b',
                                'label' => 'First Name',
                                'name' => 'first_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a8626d5882c',
                                'label' => 'Initials',
                                'name' => 'initials',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a8626d5882d',
                                'label' => 'Last Name',
                                'name' => 'last_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a8626d5882e',
                                'label' => 'Add Another',
                                'name' => 'add_another',
                                'type' => 'true_false',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'message' => '',
                                'default_value' => 0,
                                'ui' => 1,
                                'ui_on_text' => '',
                                'ui_off_text' => '',
                            ) ,
                        ) ,
                    ) ,
                    array(
                        'key' => 'field_62a8626c58825',
                        'label' => 'Author 10',
                        'name' => 'author_10',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_62a8626d5882e',
                                    'operator' => '==',
                                    'value' => '1',
                                ) ,
                            ) ,
                        ) ,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ) ,
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_62a8626d58826',
                                'label' => 'First Name',
                                'name' => 'first_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a8626d58827',
                                'label' => 'Initials',
                                'name' => 'initials',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a8626d58828',
                                'label' => 'Last Name',
                                'name' => 'last_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a8626d58829',
                                'label' => 'Add Another',
                                'name' => 'add_another',
                                'type' => 'true_false',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'message' => '',
                                'default_value' => 0,
                                'ui' => 1,
                                'ui_on_text' => '',
                                'ui_off_text' => '',
                            ) ,
                        ) ,
                    ) ,
                    array(
                        'key' => 'field_62a8626c58820',
                        'label' => 'Author 11',
                        'name' => 'author_11',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_62a8626d58829',
                                    'operator' => '==',
                                    'value' => '1',
                                ) ,
                            ) ,
                        ) ,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ) ,
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_62a8626c58821',
                                'label' => 'First Name',
                                'name' => 'first_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a8626c58822',
                                'label' => 'Initials',
                                'name' => 'initials',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a8626c58823',
                                'label' => 'Last Name',
                                'name' => 'last_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a8626c58824',
                                'label' => 'Add Another',
                                'name' => 'add_another',
                                'type' => 'true_false',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'message' => '',
                                'default_value' => 0,
                                'ui' => 1,
                                'ui_on_text' => '',
                                'ui_off_text' => '',
                            ) ,
                        ) ,
                    ) ,
                    array(
                        'key' => 'field_62a8626b5881b',
                        'label' => 'Author 12',
                        'name' => 'author_12',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_62a8626c58824',
                                    'operator' => '==',
                                    'value' => '1',
                                ) ,
                            ) ,
                        ) ,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ) ,
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_62a8626b5881c',
                                'label' => 'First Name',
                                'name' => 'first_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a8626b5881d',
                                'label' => 'Initials',
                                'name' => 'initials',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a8626b5881e',
                                'label' => 'Last Name',
                                'name' => 'last_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a8626b5881f',
                                'label' => 'Add Another',
                                'name' => 'add_another',
                                'type' => 'true_false',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'message' => '',
                                'default_value' => 0,
                                'ui' => 1,
                                'ui_on_text' => '',
                                'ui_off_text' => '',
                            ) ,
                        ) ,
                    ) ,
                    array(
                        'key' => 'field_62a8626a58816',
                        'label' => 'Author 13',
                        'name' => 'author_13',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_62a8626b5881f',
                                    'operator' => '==',
                                    'value' => '1',
                                ) ,
                            ) ,
                        ) ,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ) ,
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_62a8626a58817',
                                'label' => 'First Name',
                                'name' => 'first_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a8626a58818',
                                'label' => 'Initials',
                                'name' => 'initials',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a8626a58819',
                                'label' => 'Last Name',
                                'name' => 'last_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a8626a5881a',
                                'label' => 'Add Another',
                                'name' => 'add_another',
                                'type' => 'true_false',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'message' => '',
                                'default_value' => 0,
                                'ui' => 1,
                                'ui_on_text' => '',
                                'ui_off_text' => '',
                            ) ,
                        ) ,
                    ) ,
                    array(
                        'key' => 'field_62a8626a58811',
                        'label' => 'Author 14',
                        'name' => 'author_14',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_62a8626a5881a',
                                    'operator' => '==',
                                    'value' => '1',
                                ) ,
                            ) ,
                        ) ,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ) ,
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_62a8626a58812',
                                'label' => 'First Name',
                                'name' => 'first_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a8626a58813',
                                'label' => 'Initials',
                                'name' => 'initials',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a8626a58814',
                                'label' => 'Last Name',
                                'name' => 'last_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a8626a58815',
                                'label' => 'Add Another',
                                'name' => 'add_another',
                                'type' => 'true_false',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'message' => '',
                                'default_value' => 0,
                                'ui' => 1,
                                'ui_on_text' => '',
                                'ui_off_text' => '',
                            ) ,
                        ) ,
                    ) ,
                    array(
                        'key' => 'field_62a862695880c',
                        'label' => 'Author 15',
                        'name' => 'author_15',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_62a8626a58815',
                                    'operator' => '==',
                                    'value' => '1',
                                ) ,
                            ) ,
                        ) ,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ) ,
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_62a862695880d',
                                'label' => 'First Name',
                                'name' => 'first_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a862695880e',
                                'label' => 'Initials',
                                'name' => 'initials',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a862695880f',
                                'label' => 'Last Name',
                                'name' => 'last_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a8626958810',
                                'label' => 'Add Another',
                                'name' => 'add_another',
                                'type' => 'true_false',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'message' => '',
                                'default_value' => 0,
                                'ui' => 1,
                                'ui_on_text' => '',
                                'ui_off_text' => '',
                            ) ,
                        ) ,
                    ) ,
                    array(
                        'key' => 'field_62a8626858807',
                        'label' => 'Author 16',
                        'name' => 'author_16',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_62a8626958810',
                                    'operator' => '==',
                                    'value' => '1',
                                ) ,
                            ) ,
                        ) ,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ) ,
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_62a8626858808',
                                'label' => 'First Name',
                                'name' => 'first_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a8626858809',
                                'label' => 'Initials',
                                'name' => 'initials',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a862685880a',
                                'label' => 'Last Name',
                                'name' => 'last_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a862685880b',
                                'label' => 'Add Another',
                                'name' => 'add_another',
                                'type' => 'true_false',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'message' => '',
                                'default_value' => 0,
                                'ui' => 1,
                                'ui_on_text' => '',
                                'ui_off_text' => '',
                            ) ,
                        ) ,
                    ) ,
                    array(
                        'key' => 'field_62a8626758802',
                        'label' => 'Author 17',
                        'name' => 'author_17',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_62a862685880b',
                                    'operator' => '==',
                                    'value' => '1',
                                ) ,
                            ) ,
                        ) ,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ) ,
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_62a8626758803',
                                'label' => 'First Name',
                                'name' => 'first_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a8626758804',
                                'label' => 'Initials',
                                'name' => 'initials',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a8626758805',
                                'label' => 'Last Name',
                                'name' => 'last_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a8626758806',
                                'label' => 'Add Another',
                                'name' => 'add_another',
                                'type' => 'true_false',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'message' => '',
                                'default_value' => 0,
                                'ui' => 1,
                                'ui_on_text' => '',
                                'ui_off_text' => '',
                            ) ,
                        ) ,
                    ) ,
                    array(
                        'key' => 'field_62a86266587fd',
                        'label' => 'Author 18',
                        'name' => 'author_18',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_62a8626758806',
                                    'operator' => '==',
                                    'value' => '1',
                                ) ,
                            ) ,
                        ) ,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ) ,
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_62a86267587fe',
                                'label' => 'First Name',
                                'name' => 'first_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a86267587ff',
                                'label' => 'Initials',
                                'name' => 'initials',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                            array(
                                'key' => 'field_62a8626758800',
                                'label' => 'Last Name',
                                'name' => 'last_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ) ,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ) ,
                        ) ,
                    ) ,
                ) ,
            ) ,
            array(
                'key' => 'field_62a885f16fd92',
                'label' => 'Thumbnail',
                'name' => 'publication_thumbnail',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ) ,
                'return_format' => 'id',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ) ,
        ) ,
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'publications',
                ) ,
            ) ,
        ) ,
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));

endif;

?>
