<?php

/**
 * 
 * Register ACF fields for our people custom posts registered with inc/functions/custom-posts/ms-people-posts.php.
 * 
 */

acf_add_local_field_group( array(
	'key' => 'ms_acf_people_group',
	'title' => 'Member Details',
	'fields' => array(
		array(
			'key' => 'ms_acf_people_status_key',
			'label' => 'Status',
			'name' => 'ms_acf_people_status_name',
			'type' => 'true_false',
			'instructions' => 'Is this person a new addition to the group or are they leaving the group? If the person is leaving the group and becoming a visitor, select \'Alumni\' below and then add them to the \'Visitor\' category under \'Team Roles\'.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => 'New',
			'ui_off_text' => 'Alumni',
		),
		array(
			'key' => 'ms_acf_people_bio_key',
			'label' => 'Bio',
			'name' => 'ms_acf_people_bio_name',
			'type' => 'textarea',
			'instructions' => 'Background information and/or what they like doing outside the lab.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 6,
			'new_lines' => '',
		),
		array(
			'key' => 'ms_acf_people_assignment_key',
			'label' => 'Assignment',
			'name' => 'ms_acf_people_assignment_name',
			'type' => 'textarea',
			'instructions' => 'Short description of what this person will be doing in the group.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 6,
			'new_lines' => '',
		),
		array(
			'key' => 'ms_acf_people_email_key',
			'label' => 'Email Address',
			'name' => 'ms_acf_people_email_name',
			'type' => 'email',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'ms_acf_people_status_key',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'your.name@ru.nl',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'ms_acf_people_tel_key',
			'label' => 'Phone Number',
			'name' => 'ms_acf_people_tel_name',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'ms_acf_people_status_key',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '24 365 3323',
			'prepend' => '+31',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'ms_acf_people_office_key',
			'label' => 'Office',
			'name' => 'ms_acf_people_office_name',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'ms_acf_people_status_key',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'ms_acf_people_postcode_key',
			'label' => 'Internal Postcode',
			'name' => 'ms_acf_people_postcode_name',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'ms_acf_people_status_key',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => 1,
			'max' => 99,
			'step' => 1,
		),
		array(
			'key' => 'ms_acf_people_socials_group',
			'label' => 'Online Profiles',
			'name' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'ms_acf_people_socials_twitter_key',
					'label' => 'Twitter',
					'name' => 'ms_acf_people_socials_twitter_name',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'ms_acf_people_socials_linkedin_key',
					'label' => 'LinkedIn',
					'name' => 'ms_acf_people_socials_linkedin_name',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'ms_acf_people_socials_scholar_key',
					'label' => 'Google Scholar',
					'name' => 'ms_acf_people_socials_scholar_name',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'ms_acf_people_socials_www_key',
					'label' => 'Personal Website',
					'name' => 'ms_acf_people_socials_www_name',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'ms_people',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
));